name: CI Pipeline
on: [push]
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Make test.sh executable
        run: chmod +x ./test.sh

      - name: Run test script
        run: ./test.sh

